### ISSUE TITLE
How to remove it and revert back to original key bindings?

### ISSUE THREAD

**Issue by deadlytackler5** [rmcgibbo/jupyter_emacskeys#1]
How to remove it and revert back to original key bindings. Am on Ubuntu 16.04...

**Comment by punchagan** [comment]
You can get the location of the nbextensions directory by running the following snippet:

``` python
from notebook.nbextensions import _get_nbextension_dir
_get_nbextension_dir(user=True)  #user = False if installed as root
```

You can remove the extension from there to restore original keybindings.

**Comment by rmcgibbo** [comment]
Thanks @punchagan. Closing.
